import React, { useState } from 'react';
import { ArrowLeft, Brain, Star, Download, Loader2 } from 'lucide-react';
import { useNavigate, useLocation } from 'react-router-dom';
import jsPDF from 'jspdf';
import { getMorphology } from '../utils/morphology';

export default function DiagnosticResult() {
    const navigate = useNavigate();
    const location = useLocation();
    const [isDownloading, setIsDownloading] = useState(false);

    // Default mock data if no state is passed
    const {
        patientName = "Patient",
        thickness = "--",
        morphology = location.state?.thickness ? getMorphology(location.state.thickness) : "Trilaminar",
        diagnosis = "PENDING",
        score = "0.0",
        confidence = "95.5",
        cycleDay = "--",
        ro = "--",
        lo = "--",
        expertRec = "Review recommended by clinical lead."
    } = location.state || {};

    const handleDownload = () => {
        setIsDownloading(true);
        const doc = jsPDF();

        // Header
        doc.setFillColor(0, 122, 255); // Medical Blue
        doc.rect(0, 0, 210, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.text('VEDAENDO AI', 105, 20, { align: 'center' });
        doc.setFontSize(10);
        doc.text('CLINICAL RECEPTIVITY DIAGNOSTIC REPORT', 105, 28, { align: 'center' });

        // Doctor Info (from localStorage)
        const doctorName = localStorage.getItem('userName') || 'Dr. Specialist';
        const clinicName = localStorage.getItem('userClinic') || 'VedaEndo Medical Center';

        doc.setTextColor(0, 0, 0);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`Practitioner: ${doctorName}`, 15, 50);
        doc.text(`Facility: ${clinicName}`, 15, 55);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 155, 50);

        doc.setLineWidth(0.5);
        doc.line(15, 60, 195, 60);

        // Subject Info
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('SUBJECT INFORMATION', 15, 75);

        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.text(`Name: ${patientName}`, 20, 85);
        doc.text(`Diagnostic Cycle Day: ${cycleDay}`, 20, 92);

        // Analysis Result
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('AI ANALYSIS RESULT', 15, 110);

        doc.setFillColor(248, 251, 255);
        doc.rect(15, 115, 180, 40, 'F');

        doc.setFontSize(12);
        doc.setTextColor(0, 122, 255);
        doc.text(`RECEPTIVITY SCORE: ${score}/20`, 25, 128);

        doc.setTextColor(diagnosis === 'RECEPTIVE' ? 52 : 255, diagnosis === 'RECEPTIVE' ? 199 : 149, diagnosis === 'RECEPTIVE' ? 89 : 0);
        doc.text(`DIAGNOSIS: ${diagnosis}`, 25, 138);

        // Metrics Table
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('METRIC SUMMARY', 15, 170);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text('Endometrium Thickness:', 20, 180); doc.text(`${thickness} mm`, 70, 180);
        doc.text('Morphology Type:', 20, 187); doc.text(morphology, 70, 187);
        doc.text('Right Ovary (RO):', 20, 194); doc.text(`${ro} mm`, 70, 194);
        doc.text('Left Ovary (LO):', 20, 201); doc.text(`${lo} mm`, 70, 201);

        // Expert Recommendation
        doc.setFillColor(255, 149, 0); // Orange
        doc.rect(15, 215, 180, 25, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text('EXPERT RECOMMENDATION:', 20, 222);
        doc.setFont('helvetica', 'normal');
        doc.text(expertRec, 20, 230);

        // Footer
        doc.setTextColor(150, 150, 150);
        doc.setFontSize(8);
        doc.text('Generated by VedaEndo AI Engine. This report is for clinical evaluation by licensed medical professionals only.', 105, 280, { align: 'center' });

        // Save
        doc.save(`VedaEndo_Report_${patientName.replace(/\s+/g, '_')}.pdf`);

        setTimeout(() => setIsDownloading(false), 800);
    };

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-[#0a0f18] p-4 lg:p-8 space-y-8 pb-40 w-full">
            {/* Header */}
            <div className="flex items-center gap-4 mb-8 w-full">
                <button onClick={() => navigate(-1)} className="p-2 -ml-2 bg-white dark:bg-[#131b2b] shadow-sm hover:shadow-md rounded-full transition-all text-slate-900 dark:text-white group">
                    <ArrowLeft size={24} className="group-hover:-translate-x-1 transition-transform" />
                </button>
                <div className="flex-1">
                    <h1 className="text-2xl font-black text-slate-900 dark:text-white uppercase tracking-tight">Diagnostic Report</h1>
                    <p className="text-sm font-medium text-slate-500 mt-1">Patient: <span className="text-blue-500 font-bold">{patientName}</span></p>
                </div>
            </div>

            <div className="grid grid-cols-1 xl:grid-cols-2 gap-8 w-full">
                <div className="space-y-8">
                {/* Result Card 1 */}
                <div className="bg-white dark:bg-[#131b2b] rounded-3xl p-8 shadow-lg border border-slate-100 dark:border-slate-800/60 flex flex-col hover:border-blue-500/20 transition-colors">
                    <div className="flex justify-between items-start mb-10">
                        <div className="flex flex-col gap-2">
                            <span className="text-[13px] text-slate-400 font-black uppercase tracking-widest">Thickness Baseline</span>
                            <span className="text-4xl font-black text-slate-900 dark:text-white leading-none">{thickness} <small className="text-lg font-bold text-slate-400">mm</small></span>
                        </div>
                        <div className="flex flex-col items-end gap-2">
                            <span className="text-[13px] text-slate-400 font-black uppercase tracking-widest">Morphology</span>
                            <span className={`text-xl font-black leading-none ${morphology === 'Trilaminar' ? 'text-emerald-500' : 'text-orange-500'}`}>{morphology}</span>
                        </div>
                    </div>

                    <div className="mb-3 flex flex-col gap-3">
                        <div className="flex justify-between items-center">
                            <span className={`text-[15px] font-black tracking-widest uppercase ${diagnosis === 'RECEPTIVE' ? 'text-emerald-500' :
                                diagnosis === 'BORDERLINE' ? 'text-orange-500' : 'text-red-500'
                                }`}>
                                STATUS: {diagnosis}
                            </span>
                            <span className="text-[18px] font-black text-blue-500">{score}/20</span>
                        </div>
                        <div className="w-full h-4 bg-slate-200/60 dark:bg-slate-800 rounded-full overflow-hidden">
                            <div
                                className={`h-full bg-gradient-to-r ${diagnosis === 'RECEPTIVE' ? 'from-emerald-500 to-teal-400' :
                                    diagnosis === 'BORDERLINE' ? 'from-orange-500 to-yellow-400' : 'from-red-500 to-rose-400'
                                    } rounded-full transition-all duration-1000 ease-out shadow-lg`}
                                style={{ width: `${(parseFloat(score) / 20) * 100}%` }}
                            ></div>
                        </div>
                    </div>
                </div>

                {/* Card 3: Metric Summary */}
                <div className="bg-white dark:bg-[#131b2b] rounded-3xl p-8 flex flex-col gap-6 shadow-lg border border-slate-100 dark:border-slate-800/60 hover:border-purple-500/20 transition-colors">
                    <div className="flex items-center gap-3">
                        <Brain className="text-blue-500" size={28} />
                        <h2 className="text-[20px] font-black text-slate-900 dark:text-white tracking-tight">AI Diagnostic Insights</h2>
                    </div>

                    <p className="text-[16px] leading-relaxed text-slate-600 dark:text-slate-400 font-medium">
                        {diagnosis === 'RECEPTIVE' ?
                            'Based on the integrated hormonal baseline and follicular data, our clinical model suggests positive receptivity parameters. Subject is suitable for transfer.' :
                            diagnosis === 'BORDERLINE' ?
                                'Integrated parameters indicate borderline receptivity. Subject requires closer clinical observation and potential protocol adjustment.' :
                                'Data suggests sub-optimal receptivity parameters. Subject is not recommended for transfer in the current diagnostic cycle.'
                        }
                    </p>

                    <div className="h-[1px] bg-blue-500/10 w-full" />

                    <div className="flex justify-between items-end">
                        <div className="flex flex-col gap-1.5">
                            <span className="text-[12px] text-slate-400 font-black uppercase tracking-widest">Implantation Score</span>
                            <span className={`text-[17px] font-black uppercase tracking-wide ${diagnosis === 'RECEPTIVE' ? 'text-emerald-500' :
                                diagnosis === 'BORDERLINE' ? 'text-orange-500' : 'text-red-500'
                                }`}>
                                {diagnosis === 'RECEPTIVE' ? 'OPTIMAL' : diagnosis === 'BORDERLINE' ? 'MODERATE' : 'LOW'}
                            </span>
                        </div>
                        <div className="flex flex-col items-end gap-1.5">
                            <span className="text-[12px] text-slate-400 font-black uppercase tracking-widest">Confidence Level</span>
                            <span className="text-[22px] font-black text-blue-500">{confidence}%</span>
                        </div>
                    </div>
                </div>
                </div>

                <div className="space-y-8">
                {/* Card 3: Metric Summary */}
                <div className="bg-gradient-to-br from-[#F8FBFF] to-white dark:from-[#0a1018] dark:to-[#131b2b] border border-blue-500/30 rounded-3xl p-8 flex flex-col gap-6 shadow-lg hover:shadow-blue-500/10 transition-shadow">
                    <h2 className="text-[20px] font-black text-slate-900 dark:text-white tracking-tight">Biometric Registry</h2>

                    <div className="grid grid-cols-2 gap-y-8 gap-x-4">
                        <div className="flex flex-col gap-1.5 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl">
                            <span className="text-[11px] text-slate-400 font-black uppercase tracking-widest">Cycle Day</span>
                            <span className="text-[20px] font-black text-slate-900 dark:text-white">{cycleDay}</span>
                        </div>
                        <div className="flex flex-col gap-1.5 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl">
                            <span className="text-[11px] text-slate-400 font-black uppercase tracking-widest">Right Ovary</span>
                            <span className="text-[20px] font-black text-slate-900 dark:text-white">{ro} <small className="text-xs font-bold text-slate-400">mm</small></span>
                        </div>
                        <div className="flex flex-col gap-1.5 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl">
                            <span className="text-[11px] text-slate-400 font-black uppercase tracking-widest">Left Ovary</span>
                            <span className="text-[20px] font-black text-slate-900 dark:text-white">{lo} <small className="text-xs font-bold text-slate-400">mm</small></span>
                        </div>
                        <div className="flex flex-col gap-1.5 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-2xl">
                            <span className="text-[11px] text-slate-400 font-black uppercase tracking-widest">Endometrium</span>
                            <span className="text-[20px] font-black text-slate-900 dark:text-white">{thickness} <small className="text-xs font-bold text-slate-400">mm</small></span>
                        </div>
                    </div>
                </div>

                {/* Card 4: Expert Recommendation */}
                <div className={`${diagnosis === 'RECEPTIVE' ? 'bg-emerald-500 dark:bg-emerald-600' :
                    diagnosis === 'BORDERLINE' ? 'bg-orange-500 dark:bg-orange-600' : 'bg-red-500 dark:bg-red-600'
                    } rounded-[28px] p-6 shadow-lg shadow-blue-500/10`}>
                    <div className="flex items-center gap-3 mb-3">
                        <Star className="text-white/80" size={20} fill="currentColor" />
                        <span className="text-white font-black text-[14px] uppercase tracking-widest">Lead Recommendation</span>
                    </div>
                    <p className="text-white font-black text-[18px] leading-tight pr-4">
                        {expertRec}
                    </p>
                </div>
                </div>
            </div>

            {/* Download Report button */}
            <div className="pt-8 pb-12 w-full max-w-2xl mx-auto px-1 flex justify-center">
                <button
                    onClick={handleDownload}
                    disabled={isDownloading}
                    className="bg-black dark:bg-white text-white dark:text-black w-full h-[70px] rounded-[24px] flex justify-center items-center gap-3 shadow-2xl active:scale-95 transition-all hover:opacity-90 disabled:opacity-70"
                >
                    {isDownloading ? (
                        <>
                            <Loader2 className="animate-spin" size={24} />
                            <span className="font-black text-[18px] uppercase tracking-widest">Archiving Report...</span>
                        </>
                    ) : (
                        <>
                            <Download size={24} strokeWidth={3} />
                            <span className="font-black text-[18px] uppercase tracking-widest">Generate Clinical PDF</span>
                        </>
                    )}
                </button>
            </div>
        </div>
    );
}
