import React, { useState, useEffect } from 'react';
import {
    BarChart2, Target, Share, ChevronRight, User,
    Upload, Loader2, AlertCircle
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import API_CONFIG from '../api';
import jsPDF from 'jspdf';
import { getMorphology } from '../utils/morphology';

export default function Home() {
    const navigate = useNavigate();
    const [showPdfModal, setShowPdfModal] = useState(false);
    const [patients, setPatients] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [isDownloading, setIsDownloading] = useState(false);
    const [error, setError] = useState('');

    const handleDownloadPatientReport = (p) => {
        if (!p.is_analyzed) return;

        setIsDownloading(true);
        const doc = jsPDF();
        const score = parseFloat(p.analysis_score).toFixed(1);
        const diagnosis = parseFloat(p.analysis_score) >= 14 ? "RECEPTIVE" : "NON-RECEPTIVE";

        doc.setFillColor(0, 122, 255);
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.text('VEDAENDO AI', 105, 20, { align: 'center' });
        doc.setFontSize(10);
        doc.text('CLINICAL RECEPTIVITY DIAGNOSTIC REPORT', 105, 28, { align: 'center' });

        const doctorName = localStorage.getItem('userName') || 'Dr. Specialist';
        const clinicName = localStorage.getItem('userClinic') || 'VedaEndo Medical Center';

        doc.setTextColor(0, 0, 0);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`Practitioner: ${doctorName}`, 15, 50);
        doc.text(`Facility: ${clinicName}`, 15, 55);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 155, 50);
        doc.setLineWidth(0.5);
        doc.line(15, 60, 195, 60);

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('SUBJECT INFORMATION', 15, 75);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.text(`Name: ${p.name}`, 20, 85);
        doc.text(`Diagnostic Cycle Day: ${p.cycle_day || '--'}`, 20, 92);

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('AI ANALYSIS RESULT', 15, 110);
        doc.setFillColor(248, 251, 255);
        doc.rect(15, 115, 180, 40, 'F');
        doc.setFontSize(12);
        doc.setTextColor(0, 122, 255);
        doc.text(`RECEPTIVITY SCORE: ${score}/20`, 25, 128);
        doc.setTextColor(diagnosis === 'RECEPTIVE' ? 52 : 229, diagnosis === 'RECEPTIVE' ? 199 : 115, diagnosis === 'RECEPTIVE' ? 89 : 22);
        doc.text(`DIAGNOSIS: ${diagnosis}`, 25, 138);

        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('METRIC SUMMARY', 15, 170);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text('Endometrium Thickness:', 20, 180); doc.text(`${p.endometrium_thickness || '--'} mm`, 70, 180);
        doc.text('Morphology Type:', 20, 187); doc.text(getMorphology(p.endometrium_thickness), 70, 187);
        doc.text('Right Ovary (RO):', 20, 194); doc.text(`${p.ro_value || '--'} mm`, 70, 194);
        doc.text('Left Ovary (LO):', 20, 201); doc.text(`${p.lo_value || '--'} mm`, 70, 201);

        doc.setFillColor(255, 149, 0);
        doc.rect(15, 215, 180, 25, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text('EXPERT RECOMMENDATION:', 20, 222);
        doc.setFont('helvetica', 'normal');
        doc.text(parseFloat(p.analysis_score) >= 14 ? "Optimal receptivity. Proceed with clinical protocol." : "Low receptivity score. Clinical review recommended.", 20, 230);

        doc.setTextColor(150, 150, 150);
        doc.setFontSize(8);
        doc.text('Generated by VedaEndo AI Engine. This report is for clinical evaluation by licensed medical professionals only.', 105, 280, { align: 'center' });

        doc.save(`VedaEndo_Report_${p.name.replace(/\s+/g, '_')}.pdf`);
        setTimeout(() => setIsDownloading(false), 800);
    };

    const userName = localStorage.getItem('userName') || 'Medical Professional';
    const userEmail = localStorage.getItem('userEmail');

    useEffect(() => {
        const fetchPatients = async () => {
            if (!userEmail) { navigate('/login'); return; }
            try {
                const userToken = localStorage.getItem('userToken');
                const response = await fetch(API_CONFIG.PATIENTS.LIST(userEmail), {
                    headers: { 'Authorization': `Bearer ${userToken}` }
                });
                const data = await response.json();
                if (response.ok) setPatients(data);
                else setError('Failed to load patient records');
            } catch (err) {
                setError('Connection to clinical server lost');
                console.error('Fetch error:', err);
            } finally {
                setIsLoading(false);
            }
        };
        fetchPatients();
    }, [userEmail, navigate]);

    const stats = {
        total: patients.length,
        successful: patients.filter(p => parseFloat(p.analysis_score) >= 14 && p.is_analyzed).length,
        actionRequired: patients.filter(p => parseFloat(p.analysis_score) < 14 && p.is_analyzed).length,
        unauthorized: patients.filter(p => !p.is_analyzed).length
    };
    const successRate = stats.total > 0 ? ((stats.successful / stats.total) * 100).toFixed(1) : 0;
    const actionRate = stats.total > 0 ? ((stats.actionRequired / stats.total) * 100).toFixed(1) : 0;



    return (
        <div className="min-h-screen bg-slate-50 dark:bg-[#0a0f18] p-4 lg:p-8 pb-32 w-full">
            {/* Header */}
            <div className="flex justify-between items-center mb-10 w-full">
                <div
                    className="flex gap-4 cursor-pointer active:scale-95 transition-transform"
                    onClick={() => navigate('/profile')}
                >
                    <div className="relative">
                        <div className="w-14 h-14 bg-white dark:bg-slate-800 rounded-full flex items-center justify-center shadow-md border-2 border-white dark:border-slate-800">
                            <User className="text-slate-400" size={32} />
                        </div>
                        <div className="absolute bottom-0 right-0 w-3.5 h-3.5 bg-green-500 rounded-full border-2 border-white dark:border-slate-800"></div>
                    </div>
                    <div className="flex flex-col justify-center">
                        <span className="text-sm font-medium text-slate-500">Good Morning</span>
                        <h1 className="text-xl font-bold text-slate-900 dark:text-white leading-tight">
                            {userName.startsWith('Dr.') ? userName : `Dr. ${userName}`}
                        </h1>
                        <span className="text-xs font-semibold text-blue-500 mt-0.5">Medical Specialist</span>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 xl:grid-cols-3 gap-8 w-full">
                {/* Left Column: Analysis Overview (Spans 2 columns on xl) */}
                <div className="xl:col-span-2 space-y-6">
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                        <BarChart2 className="text-blue-500" /> Analysis Overview
                    </h2>

                {/* Main Stats Card */}
                <div className="bg-white dark:bg-[#1a1a1a] rounded-2xl p-6 shadow-md shadow-slate-200/50 dark:shadow-none border border-slate-100 dark:border-slate-800">
                    <div className="flex justify-between items-center mb-6">
                        <div>
                            <p className="text-sm font-medium text-slate-500">Total Analyzed</p>
                            <h3 className="text-4xl font-extrabold text-slate-900 dark:text-white">{stats.total}</h3>
                        </div>
                        <div className="w-14 h-14 bg-blue-50 dark:bg-blue-900/20 rounded-xl flex items-center justify-center text-blue-500">
                            <BarChart2 size={30} fill="currentColor" />
                        </div>
                    </div>
                    <div className="h-px w-full bg-slate-100 dark:bg-slate-800 mb-6"></div>
                    <div className="flex gap-10">
                        <div className="flex flex-col gap-1">
                            <div className="flex items-center gap-2">
                                <div className="w-2 h-2 rounded-full bg-green-500"></div>
                                <span className="text-xs text-slate-500 font-medium">Successful</span>
                            </div>
                            <span className="text-xl font-bold text-green-500">{stats.successful}</span>
                            <span className="text-xs text-slate-400">{successRate}%</span>
                        </div>
                        <div className="flex flex-col gap-1">
                            <div className="flex items-center gap-2">
                                <div className="w-2 h-2 rounded-full bg-orange-500"></div>
                                <span className="text-xs text-slate-500 font-medium">Action Required</span>
                            </div>
                            <span className="text-xl font-bold text-orange-500">{stats.actionRequired}</span>
                            <span className="text-xs text-slate-400">{actionRate}%</span>
                        </div>
                    </div>
                </div>

                    {/* Stats Summary Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="bg-white dark:bg-[#131b2b] rounded-3xl p-6 shadow-lg border border-slate-100 dark:border-slate-800/60 flex flex-col gap-3 group hover:border-purple-500/30 transition-colors">
                            <Target className="text-purple-500 group-hover:scale-110 transition-transform" size={24} />
                            <div>
                                <h4 className="text-3xl font-extrabold text-slate-900 dark:text-white">94.2%</h4>
                                <p className="text-sm text-slate-500 font-medium mt-1">Avg. AI Accuracy</p>
                            </div>
                        </div>
                        <button
                            onClick={() => setShowPdfModal(true)}
                            className="text-left bg-gradient-to-br from-blue-500 to-blue-600 rounded-3xl p-6 shadow-lg shadow-blue-500/25 flex flex-col gap-3 hover:from-blue-600 hover:to-blue-700 transition-colors group"
                        >
                            <Share className="text-white group-hover:scale-110 transition-transform" size={24} />
                            <div>
                                <h4 className="text-3xl font-extrabold text-white">Share</h4>
                                <p className="text-sm text-blue-100 font-medium mt-1">Export Clinical PDF</p>
                            </div>
                        </button>
                    </div>
                </div>

                {/* Right Column: Recent Patients */}
                <div className="space-y-6">
                    <div className="flex justify-between items-center">
                        <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                            <User className="text-blue-500" /> Recent Patients
                        </h2>
                    <button
                        onClick={() => navigate('/registry/active')}
                        className="text-sm font-semibold text-blue-500 hover:text-blue-600 flex items-center gap-1"
                    >
                        See All {patients.length > 0 && <span className="bg-blue-500 text-white text-[10px] font-black px-2 py-0.5 rounded-full ml-1">{patients.length}</span>}
                    </button>
                </div>

                <div className="flex flex-col gap-3">
                    {isLoading ? (
                        <div className="flex flex-col items-center justify-center py-12 text-slate-400">
                            <Loader2 className="animate-spin mb-2" size={32} />
                            <span className="font-bold text-sm">Loading clinical data...</span>
                        </div>
                    ) : error ? (
                        <div className="bg-red-500/10 border border-red-500/20 rounded-2xl p-4 flex items-center gap-3 text-red-600 dark:text-red-400 text-sm font-bold">
                            <AlertCircle size={20} />
                            <span>{error}</span>
                        </div>
                    ) : patients.length === 0 ? (
                        <div className="text-center py-12 bg-white dark:bg-[#1a1a1a] rounded-3xl border-2 border-dashed border-slate-200 dark:border-slate-800">
                            <p className="text-slate-500 font-bold">No patient records found.</p>
                        </div>
                    ) : (
                        patients.slice(0, 5).map(patient => (
                            <PatientCard
                                key={patient.id}
                                name={patient.name}
                                condition={patient.condition}
                                id={patient.medical_id}
                                date={patient.last_visit}
                                isOnline={patient.is_online}
                                onClick={() => navigate(`/registry/patient/${patient.id}`, { state: { patient } })}
                            />
                        ))
                    )}
                </div>
            </div>
            </div>
            {/* PDF Share Modal */}
            {showPdfModal && (
                <div className="fixed inset-0 z-50 flex flex-col justify-end bg-black/40 backdrop-blur-sm animate-fade-in" onClick={() => setShowPdfModal(false)}>
                    <div
                        className="bg-slate-50 dark:bg-[#1a1a1a] w-full rounded-t-[32px] p-6 pb-12 animate-slide-up"
                        onClick={(e) => e.stopPropagation()}
                    >
                        <div className="flex items-center justify-between mb-6">
                            <div className="w-20"></div>
                            <h3 className="text-lg font-bold text-slate-900 dark:text-white text-center flex-1">Select Patient Report</h3>
                            <div className="w-20 flex justify-end">
                                <button
                                    onClick={() => setShowPdfModal(false)}
                                    className="text-slate-700 dark:text-slate-300 font-medium px-4 py-2 bg-white dark:bg-slate-800 rounded-full shadow-[0_2px_8px_rgba(0,0,0,0.05)] text-[15px]"
                                >
                                    Cancel
                                </button>
                            </div>
                        </div>

                        <div className="bg-white dark:bg-slate-900 rounded-[28px] p-2 shadow-sm max-h-[400px] overflow-y-auto">
                            {patients.length > 0 ? patients.map((p, idx, arr) => (
                                <div key={p.id}>
                                    <div
                                        className="flex items-center justify-between p-4 cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-800 rounded-2xl transition-colors group"
                                        onClick={() => handleDownloadPatientReport(p)}
                                    >
                                        <div className="flex items-center gap-4">
                                            <div className={`w-12 h-12 rounded-2xl flex items-center justify-center font-black text-lg ${p.is_analyzed ? 'bg-blue-500/10 text-blue-500' : 'bg-slate-100 text-slate-400'}`}>
                                                {p.name.charAt(0)}
                                            </div>
                                            <div>
                                                <h4 className="font-black text-slate-900 dark:text-white text-[17px] tracking-tight group-hover:text-blue-500 transition-colors">{p.name}</h4>
                                                <p className="text-[11px] font-bold text-slate-400 uppercase tracking-widest">Patient ID: {p.medical_id}</p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-4">
                                            {!p.is_analyzed ? (
                                                <span className="text-[10px] font-black bg-slate-100 dark:bg-slate-800 text-slate-500 px-3 py-1.5 rounded-full uppercase tracking-widest">No Analysis</span>
                                            ) : (
                                                <span className={`text-[10px] font-black px-3 py-1.5 rounded-full uppercase tracking-widest ${parseFloat(p.analysis_score) >= 14 ? 'bg-emerald-500/10 text-emerald-500' : 'bg-orange-500/10 text-orange-500'}`}>
                                                    {parseFloat(p.analysis_score) >= 14 ? 'Optimal' : 'Moderate'}
                                                </span>
                                            )}
                                            <button className={`${p.is_analyzed ? 'text-blue-500' : 'text-slate-300 pointer-events-none'} transition-transform active:scale-90`}>
                                                <Upload size={22} className="rotate-180" />
                                            </button>
                                        </div>
                                    </div>
                                    {idx !== arr.length - 1 && (
                                        <div className="h-[1px] bg-slate-100 dark:bg-slate-800 mx-4 opacity-50" />
                                    )}
                                </div>
                            )) : (
                                <div className="p-12 text-center text-slate-500 font-bold italic">No patient records in digital registry.</div>
                            )}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}



function PatientCard({ name, condition, id, date, isOnline, onClick }) {
    return (
        <div
            className="flex items-center gap-4 bg-white dark:bg-[#1a1a1a] p-4 rounded-xl shadow-sm border border-slate-100 dark:border-slate-800 cursor-pointer hover:shadow-md transition-shadow"
            onClick={onClick}
        >
            <div className="relative">
                <div className="w-12 h-12 rounded-full bg-blue-50 dark:bg-blue-900/20 flex items-center justify-center text-blue-500">
                    <User fill="currentColor" size={22} className="opacity-80" />
                </div>
                {isOnline && <div className="absolute bottom-0 right-0 w-3.5 h-3.5 bg-green-500 rounded-full border-2 border-white dark:border-[#1a1a1a]"></div>}
            </div>
            <div className="flex-1 flex flex-col justify-center">
                <div className="flex justify-between items-center">
                    <span className="font-semibold text-sm text-slate-900 dark:text-white">{name}</span>
                    <span className="text-xs text-slate-400">{date}</span>
                </div>
                <span className="text-xs text-slate-500 truncate mt-0.5">{condition}</span>
                <span className="text-[10px] text-slate-400 mt-1">Patient ID: {id}</span>
            </div>
            <ChevronRight className="text-slate-400" size={16} />
        </div>
    );
}
